# Generated by Django 2.2.4 on 2020-04-01 16:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200401_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='normalised_owners_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца:'),
        ),
    ]
