# Generated by Django 2.2.4 on 2020-04-03 20:39

from django.db import migrations
from django.apps import apps

def move_owners_info(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    owners = apps.get_model('property', 'Owner')

    for flat in flats.objects.all():

        owners.objects.get_or_create(owner=flat.owner, defaults={
            'owners_phonenumber': flat.owners_phonenumber,
            'normalised_owners_phonenumber': flat.normalised_owners_phonenumber,
        }
                                     )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200403_2325'),
    ]

    operations = [
        migrations.RunPython(move_owners_info),
    ]
