# Generated by Django 2.2.4 on 2020-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20200413_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='own_flats',
            field=models.ManyToManyField(blank=True, related_name='flat_owners', to='property.Flat', verbose_name='Квартиры в совственности'),
        ),
    ]
