# Generated by Django 2.2.4 on 2020-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20200414_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='normalised_owners_phonenumber',
            new_name='normalized_owners_phonenumber',
        ),
    ]
